### ISSUE TITLE
lose information  :（

### ISSUE THREAD

**Issue by yaojl2006** [kermitt2/pdf2xml#6]
Hi,
I find that the pdf2xml component sometimes will lose some information of pdf which influences the performance of grobid.

I've sent 4 typical pdf that pdf2xml can't analyze well to your email. If you need more articles,I'll try to collect more of these stuff for you. Hope it can help you. :）

**Comment by kermitt2** [comment]
Hi @yaojl2006 
Thanks this is very useful! 
Indeed this is one of the main issue for GROBID for processing correctly header for instance, and we are working on improving pdf2xml.
However I didn't receive the pdf on my email - did you use patrice.lopez@science-miner.com ?

**Comment by yaojl2006** [comment]
Hi,
Sorry,i had thought you used the github email. Now I just send to  the correct email. )
